spring:
  datasource:
    username: 'app'
    password: '123456'
    url: 'jdbc:postgresql://1349291-cu57808.tw1.ru:5432/monotordb'
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
management:
  endpoint:
    health:
      probes:
        enabled: true
mqtt:
  broker-url: 'tcp://mqtt.eclipseprojects.io:1883'
  topics: 'smkt/geo'